# Generated by Django 5.1.15 on 2026-05-17 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('categorie', models.CharField(choices=[('alimentaire', 'Aide alimentaire'), ('scolaire', 'Fournitures scolaires'), ('medical', 'Aide médicale'), ('sensibilisation', 'Sensibilisation'), ('fete', 'Fête annuelle')], max_length=50)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nb_beneficiaires', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('contenu', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/')),
                ('publie', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BilanAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField(unique=True)),
                ('recettes_fete', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recettes_dons', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('depenses_ait', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('depenses_scolaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde_banque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('solde_caisse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('nb_enfants_aides', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-annee'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Don',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_donateur', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('message', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('anonyme', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MembreBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('presidente', 'Présidente'), ('vice_presidente', 'Vice-Présidente'), ('secretaire', 'Secrétaire'), ('secretaire_adjoint', 'Secrétaire Adjoint(e)'), ('tresoriere', 'Trésorière'), ('charges_affaires', "Chargé(e) d'affaires sociales"), ('charges_affaires_adj', "Chargé(e) d'affaires sociales adjoint(e)")], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bureau/')),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
