# Generated by Django 5.2.15 on 2026-06-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='video_url',
            field=models.URLField(blank=True, help_text='Collez ici le lien YouTube de la video (exemple: https://www.youtube.com/watch?v=XXXXXXXXX)', null=True),
        ),
    ]
