# Generated by Django 5.2.15 on 2026-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_actualite_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='video_url',
            field=models.URLField(blank=True, help_text='Collez ici le lien YouTube de la video (exemple: https://www.youtube.com/watch?v=XXXXXXXXX)', null=True),
        ),
    ]
