# Generated by Django 5.2.15 on 2026-07-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_update_bilans'),
        ('main', '0004_action_video_url'),
    ]

    operations = [
    ]
