# Generated by Django 5.2.17 on 2026-09-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membrebureau',
            name='role',
            field=models.CharField(choices=[('presidente', 'Présidente'), ('vice_presidente', 'Vice-Présidente'), ('secretaire', 'Secrétaire'), ('secretaire_adjoint', 'Secrétaire Adjoint(e)'), ('tresoriere', 'Trésorière'), ('charges_affaires', "Chargé(e) d'affaires sociales"), ('charges_affaires_adj', "Chargé(e) d'affaires sociales adjoint(e)"), ('collaborateur', 'Collaborateur')], max_length=50),
        ),
    ]
