# Generated by Django 5.2.17 on 2026-09-09 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_membrebureau_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='video_file',
            field=models.FileField(blank=True, help_text='Ou envoyez directement un fichier video (prioritaire sur le lien YouTube si les deux sont remplis).', null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='video_file',
            field=models.FileField(blank=True, help_text='Ou envoyez directement un fichier video (prioritaire sur le lien YouTube si les deux sont remplis).', null=True, upload_to='videos/'),
        ),
    ]
