# Generated by Django 5.2.17 on 2026-09-09 18:17

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_action_video_file_actualite_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='video_file',
            field=models.FileField(blank=True, help_text='Ou envoyez directement un fichier video, 25 Mo maximum (prioritaire sur le lien YouTube si les deux sont remplis).', null=True, upload_to='videos/', validators=[main.models.validate_video_size]),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='video_file',
            field=models.FileField(blank=True, help_text='Ou envoyez directement un fichier video, 25 Mo maximum (prioritaire sur le lien YouTube si les deux sont remplis).', null=True, upload_to='videos/', validators=[main.models.validate_video_size]),
        ),
    ]
